apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-persistent-volume-claim
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ludovicofabbri/Documents/Docker/multi-k8s/db-data"